on:
  push: 
    branches: [main]
  workflow_dispatch:
    inputs:
      homedrive:
        description: The home drive on the machine
        required: true
      logLevel:
         description: Log level
         type: choice
         default: warning
         options:
           - info
           - warning
           - debug
      tag:
        description: Require tag after run
        type: boolean
        required: true

name: My first work flow

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "👋 Hello World!"
      
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: List files in repository
        run: |
            echo "The repository ${{ github.repository }} contains the following files:"
            tree
      - name: log
        run: |
            echo "homedrive: ${{ inputs.homedrive }}"
            echo "logLevel: ${{ inputs.logLevel }}"
            echo "tag: ${{ inputs.tag }}"
        if: ${{ github.event_name == 'workflow_dispatch' }}

